[package]
name = "canter-connector"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core-foundation = "0.9"
libc = "0.2"
uuid = { version = "0.8", features = ["serde", "v4"] }
