[package]
authors = ["Han Lee <hanlee.dev@gmail.com>"]
name = "canter-connector"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
canter = { path = "../.." }
core-foundation = "0.9"
libc = "0.2"
napi = "1"
napi-derive = "1"

[build-dependencies]
napi-build = "1"

[profile.release]
lto = true
